title: Fadullo
author: Fadullo
description: Currently doing a BSc Major in Physics combined with a D.Met (Diploma in Meteorology) and a Minor in Math. Interested in weather, computing, Vim.
avatar: "./assets/images/lecture.jpg"
url: "https://fadullo.github.io"
baseurl: "/blog"

exclude:
  - archive

social_links:
  - platform: github
    user_url: "https://github.com/fadullo"
  - platform: tiktok
    user_url: "https://www.tiktok.com/@fadullophysics"
  # - platform: twitter
  #   user_url: "https://x.com/fadullotwt"
  - platform: instagram
    user_url: "https://instagram.com/fadulloig"
  - platform: spotify
    user_url: "https://open.spotify.com/user/4wrnu63xlunbdovbv9m6toq0o"


plugins:
  - jekyll-feed

